gateway:
  routes:
    - id: campaign-api
      uri: http://campaign-api.stage.svc.cluster.local:8081
    - id: google-ads-api
      uri: http://google-ads-api.stage.svc.cluster.local:8082

# OpenAPI properties
springdoc:
  swagger-ui:
    enabled: false

logging:
  level:
    io.micrometer.tracing: WARN
    org.springframework.web: WARN
